# python code linter
# from: https://github.com/ricardochaves/python-lint


name: "Python Code Quality and Lint"

#############################
# Start the job on all push #
#############################
on: [push]

###############
# Set the Job #
###############
jobs:
  lint:
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ############################
      ## Checkout the code base ##
      ############################
      - name: Checkout Code
        uses: actions/checkout@v1

      ##################################
      ## Run Linter against code base ##
      ##################################
      - name: Lint Python Code
        uses: ricardochaves/python-lint@v1.3.0
        with:
          python-root-list: "scalesec_gcp_workload_identity tests examples"
          use-pylint: true
          use-pycodestyle: false
          use-flake8: false
          use-black: false
          use-mypy: false
          use-isort: false
          extra-pylint-options: "--rcfile .github/workflows/configs/.pylintrc"
          extra-pycodestyle-options: ""
          extra-flake8-options: ""
          extra-black-options: ""
          extra-mypy-options: ""
          extra-isort-options: ""
